services:
  # Frontend - Desenvolvimento
  frontend-dev:
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - docker.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - biblioteca-network

networks:
  biblioteca-network:
    driver: bridge

volumes:
  node_modules:
